export const Names = {
  accept: "Akceptuj",
  action_flag: "Action flag",
  action_time: "Action time",
  actions: "Akcje",
  admission_date: "Data przyjęcia",
  catalog_no: "Numer katalogowy",
  change_message: "Change message",
  comment: "Komentarz",
  concentration: "Stężenie",
  content_type: "Content type",
  count: "Ilość",
  details: "Szczegóły",
  disinfectant: "Środek dezynfekujący",
  email: "Email",
  error_occurred: "Wystąpił błąd",
  expiration_date: "Data ważności",
  first_name: "Imię",
  general_info: "Informacje ogólne",
  generate_usage_record: "Wygeneruj kartę rozchodu",
  hazards: "Piktogramy",
  home_page: "Strona główna",
  id: "ID",
  initials: "Inicjały",
  is_archived: "Zarchiwizowany",
  is_disinfectant: "Środek dezynfekujący",
  is_kit: "Zestaw",
  is_staff: "Administrator",
  is_usage_record_generated: "Wygenerowano kartę rozchodu",
  is_usage_record_required: "Wymagana karta rozchodu",
  lab_roles: "Role",
  laboratory: "Laboratorium",
  last_name: "Nazwisko",
  location: "Lokalizacja",
  login: "Zaloguj",
  logout: "Wyloguj",
  lot_no: "LOT",
  name: "Nazwa",
  object_id: "ID Obiektu",
  object_repr: "Object Repr",
  ok: "Ok",
  opening_and_check_date: "Data otwarcia",
  password: "Hasło",
  password_confirm: "Potwierdź hasło",
  preview: "podgląd",
  producer: "Producent",
  purity: "Czystość",
  quantity: "Ilość",
  reagent: "Odczynnik",
  reagent_name: "Nazwa odczynnika",
  reagents: "Odczynniki",
  refresh: "Odśwież",
  reject: "Odrzuć",
  requester: "Zgłaszający",
  requester_comment: "Komentarz zgłaszającego",
  room: "Pokój",
  safety_data_sheet: "Karta charakterystyki",
  safety_instruction: "Instrukcja bezpieczeństwa",
  send: "Wyślij",
  storing_temperature: "Temperatura przechowywania",
  supervisor: "Kierownik",
  title_add_personal_reagent: "Wprowadź nowy odczynnik osobisty",
  title_add_reagent: "Nowy odczynnik",
  title_add_user: "Nowy użytkownik",
  title_expiration_date: "Kończące się daty ważności",
  title_logs: "Logi",
  title_personal_reagent_list_me: "Lista moich odczynników",
  title_personal_reagent_request_list: "Wszystkie odczynniki osobiste",
  title_reagents_grid: "Odczynniki",
  title_safety_instructions: "Instrukcje bezpieczeństwa",
  title_usage_record_notifications: "Brakujące karty rozchodu",
  title_users: "Użytkownicy",
  unit: "Jednostka",
  usage_record: "Karta rozchodu",
  user: "Użytkownik",
  username: "Nazwa użytkownika",
  title_edit_personal_reagent: "Edytuj odczynnik osobisty",
  producers: "Producenci",
  abbreviation: "Skrót",
  title_add_producer: "Nowy producent",
  units: "Jednostki",
  title_add_unit: "Nowa jednostka",
  group: "Grupa",
  classification: "Klasyfikacja",
  pictogram: "Piktogram",
  title_add_pictogram: "Nowy piktogram",
  usages: "Klasa i kategoria zagrożenia",
  edit: "Edycja",
  new: "Nowy",
  status: "Status",
  responder_comment: "Komentarz zwrotny",
  change_status_date: "Data zmiany statusu",
  producer_name: "Nazwa producenta",
  brand_name: "Nazwa marki",
  producer_abbreviation: "Skrót nazwy producenta/marki",
  type: "Typ",
  reagent_types: "Typy odczynników",
  title_add_reagent_type: "Dodaj nowy typ odczynnika",
  storage_conditions: "Warunki przechowywania",
  title_add_storage_condition: "Dodaj nowe warunki przechowywania",
  title_add_purity_quality: "Dodaj nową czystość/jakość",
  code: "Kod",
  phrase: "Tekst zwrotu",
  new_item: "dodaj nowy",
  log_in: "Zaloguj się",
  no_permissions_description:
    "Nie masz uprawnień, aby wyświetlić tę stronę. Zaloguj się na konto z odpowiednimi uprawnieniami.",
  no_permissions: "Brak uprawnień",
  page_not_found: "Ups! Strona nie została znaleziona",
  page_not_found_description:
    "Strona, którą próbujesz odwiedzić, nie istnieje. Sprawdź, czy adres URL jest poprawny, lub wróć na stronę główną.",
  logs: "Logi",
  users: "Użytkownicy",
  project_groups: "Grupy Projektowe",
  reagent_passing: "Przekazywanie odczynników",
  precautionary_statements: "Kody P",
  purities_qualities: "Czystość/Jakość",
  added_new_object_id: "Dodano nowy obiekt, ID:",
  delete: "Usuń",
  delete_confirmation_title: "Potwierdź usunięcie",
  delete_confirmation_description: "Czy na pewno chcesz usunąć ten obiekt?",
  removed: "Usunięto",
  updated_object_id: "Zaktualizowano obiekt, ID:",
  add_new: "Dodaj nowy",
  personal_reagents: "Odczynniki osobiste",
  look_at_archived: "Przeglądaj archiwalne",
  passwords_not_match: "Wprowadzone hasła nie są identyczne.",
  updated: "Zaktualizowano",
  personal_reagents_form_based_info: "Podstawowe informacje",
  clp_classification: "Klasyfikacja CLP",
  hazard_group: "Grupa zagrożenia",
  clp_classifications: "Klasyfikacje CLP",
  classifications: "Klasyfikacje",
  concentrations: "Stężenia",
  not_verified: "Niezweryfikowane przez administratora",
  pictograms: "Piktogramy",
  hazard_class: "Klasa zagrożenia",
  hazard_category: "Kategoria zagrożenia",
  hazard_and_category_code: "Zagrożenia i kod kategorii",
  signal_word: "Ostrzeżenie",
  hazard_statements: "Kody H",
  project_procedures: "Procedury projektowe",
  manager: "Kierownik procedury",
  workers: "Pracownicy",
  close: "Zamknij",
  main_owner: "Główny użytkownik",
  receipt_purchase_date: "Data zakupu",
  disposal_utilization_date: "Data utylizacji",
  project_procedure: "Procedura projektowa",
  user_comment: "Komentarz",
  detailed_location: "Szczegółowa lokalizacja",
  is_critical: "Odczynnik kluczowy",
  purity_quality: "Czystość/Jakość",
  volume: "Objętość opakowania",
  cas_no: "Nr CAS substancji",
  other_info: "Inne informacje o odczynniku",
  kit_contents: "Skład zestawu",
  is_validated_by_admin: "Zweryfikowany przez administratora",
  loading_data: "Ładowanie danych...",
  all: "wszystkie",
  search: "Szukaj",
  my_personal_reagents: "Moje odczynniki osobiste",
  reagent_requests_description:
    "Aby wysłać nową prośbę o przekazanie odczynnika, kliknij przycisk akcji 'Wyślij prośbę' przy wybranym odczynniku w zakładce 'Odczynniki osobiste'",
  archived: "ARCHIWALNE",
  sanepid_pip_report: "Raport dla Sanepidu i PIP",
  lab_manager_report: "Raporty Kierownika Laboratorium",
  project_procedure_report: "Raport do Projektu/Procedury",
  reports: "Raporty",
  statistics: "Statystyki",
  lp: "Lp.",
  year: "Rok",
  procedure: "Procedura",
  worker_personal_reagents:
    "Liczba sztuk poszczególnych odczynników przypisanych do pracownika",
  worker_disposed_utilized_personal_reagents:
    "Statystyka odczynnika > ile sztuk danego odczynnika zostało zakupionych i zużytych/zutylizowanych  w danym roku kalendarzowym",
  project_procedure_personal_reagents:
    "Liczba sztuk poszczególnych odczynników przypisanych do danego projektu",
  project_procedure_disposed_utilized_personal_reagents:
    "Statystyka odczynników Procedury/Projektu > ile sztuk danego odczynnika zostało zakupionych i zużytych/zutylizowanych  w danym roku kalendarzowym w danym projekcie",
  laboratory_personal_reagents:
    "Liczba sztuk poszczególnych odczynników przypisanych do danego Laboratorium",
  laboratory_disposed_utilized_personal_reagents:
    "Statystyka odczynników Laboratorium > ile sztuk danego odczynnika zostało zakupionych i zużytych/zutylizowanych  w danym roku kalendarzowym w danym Laboratorium",
  top10_laboratory_personal_reagents:
    "TOP 10 - 10 najczęściej kupowanych odczynników w Laboratorium",
  top20_laboratory_personal_reagents:
    "TOP 20 - 20 najczęściej kupowanych odczynników  w Laboratorium",
  global_personal_reagents:
    "Liczba sztuk poszczególnych odczynników globalnie w bazie",
  global_disposed_utilized_personal_reagents:
    "Statystyka odczynników globalna > ile sztuk danego odczynnika zostało zakupionych i zużytych/zutylizowanych  w danym roku kalendarzowym we wszystkich Labach łącznie (w bazie)",
  no_data_to_show: "Brak danych do wyświetlenia",
  fill_filters_to_show_data: "Uzupełnij filtry, aby wyświetlić dane",
  project_procedure_name: "Nazwa projektu/procedury",
  report_header: "Nazwa raportu",
  successfully_generated_report:
    "Raport został wygenerowany. Pobieranie rozpocznie się automatycznie.",
  project_procedure_report_name: "ProjektProceduraRaport",
  lab_manager_report_name: "KierownikLaboratoriumRaport",
  sanepid_pip_report_name: "SanepidPIPRaport",
  filters: "Filtry",
  report_name_desc_field:
    "Aby zmodyfikować domyślny nagłówek raportu, uzupełnij pole poniżej.",
  report_filters_description:
    "Domyślnie raporty generowane są dla wszystkich odczynników. Poniższe filtry zostaną uwzględnione w raporcie.",
  statistics_desc:
    "Rozwiń sekcję, aby wyświetlić odpowiadające jej statystyki.",
  reagent_expired: "Odczynniki przeterminowane",
  reagent_not_expired: "Odczynniki nieprzeterminowane",
  custom_date: "Wybierz niestandardową datę",
  sign: "Znak",
  no_reagents_waiting_for_approval: "Brak zgłoszeń oczekujących na akceptację.",
  table_name: "Nazwa tabeli",
  fields_awaiting_for_approval: "Pola oczekujące na akceptację",
  reagent_moved_to_archive: "Odczynnik został przeniesiony do archiwum.",
  updated_reagent: "Właściwości odczynnika zostały zaktualizowane.",
  Producer: "Producent",
  Unit: "Jednostka",
  ReagentType: "Typ odczynnika",
  StorageCondition: "Warunki przechowywania",
  PurityQuality: "Czystość/Jakość",
  PrecautionaryStatement: "Kody P",
  ClpClassification: "Klasyfikacja CLP",
  Classification: "Klasyfikacja",
  HazardStatement: "Kody H",
  Concentration: "Stężenie",
  ProjectProcedure: "Procedura projektowa",
  Pictogram: "Piktogram",
  ReagentRequest: "Prośba o przekazanie odczynnika",
  Reagent: "Odczynnik",
  all_fields_verified: "Wszystkie pola zostały zweryfikowane.",
  count_entered_reagents: "Liczba wprowadzonych odczynników osobistych",
  updated_personal_reagent: "Odczynnik osobisty został zaktualizowany.",
  safety_instruction_was_open_in_new_card:
    "Instrukcja bezpieczeństwa została otwarta w nowej karcie.",
  reagent_request_accepted:
    "Zaakceptowano prośbę. Odczynnik został przekazany.",
  reagent_request_rejected:
    "Odrzucono prośbę. Odczynnik nie został przekazany.",
  safety_data_sheet_name: "Nazwa Karty Charakterystyki",
  safety_instruction_name: "Nazwa Instrukcji Bezpieczeństwa",
  authors: "Autorzy",
  last_login: "Ostatnio zalogowany",
  is_usage_record_required_tooltip:
    "Odczynnik musi posiadać kartę rozchodu, gdy: \n 1. Posiada kody H, które wymagają karty rozchodu, \n 2. Jest metanolem lub zawiera metanol (preparaty o stężeniach metanolu wyższych niż 3 %)",
  ghs_hazard_statements: "Piktogramy GHS",
  generate_usage_record_for_reagents:
    "Wygeneruj kartę rozchodu dla odczynników",
  all_reagents_have_generated_usage_record:
    "Wszystkie odczynniki mają wygenerowaną kartę rozchodu.",
  yes: "Tak",
  no: "Nie",
  personal_reagents_report_name: "odczynniki-osobiste",
  few_critical_notifications: "Niski stan kluczowych odczynników",
  left: "Pozostało",
  show_history: "Pokaż historię zmian",
  history_id: "ID zmiany",
  history_change_reason: "Powód zmiany",
  history_date: "Data zmiany",
  history_user: "Zmienione przez",
  history_type: "Typ zmiany",
  show_back_history: "Powrót do listy",
  logs_desc: "Rozwiń sekcję, aby wyświetlić odpowiadające jej logi.",
  change_history: "Historia zmian",
  legend: "Legenda",
  storage_condition: "Warunki przechowywania",
  cancel: "Anuluj",
  back: "Powrót",
  user_manual: "Instrukcja obsługi",
  update_user_manual: "Wgraj nową instrukcję",
  log_in_button: "Logowanie",
  updated_user_manual: "Instrukcja obsługi została zaktualizowana.",
  user_manual_in_new_card:
    "Instrukcja bezpieczeństwa otworzy się w nowej karcie",
  open: "Otwórz",
  user_manual_not_found: "Nie znaleziono instrukcji obsługi",
  authors_header: "Zespół zaangażowany w proces tworzenia produktu:",
  app_info: "Informacje o aplikacji",
  app_description:
    "Aplikacja do zarządzania odczynnikami chemicznymi w laboratorium.",
};

type T = keyof typeof Names;

export const getName = (name: T) => {
  return (
    Names[name] || Names[name.split(".").slice(-1).toString() as T] || name
  );
};
